### ISSUE TITLE
Feature: User can get hot tracks

### ISSUE THREAD

**Issue by jameswu49** [jameswu49/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see a list of the hottest tracks 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks the hottest tab, they will see a list of the hottest tracks from the api 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-01-09 at 12 00 50 PM](https://user-images.githubusercontent.com/107448164/211397187-a0ad91f0-c746-491d-86bb-8d822159f13b.png)

![Screenshot 2023-01-09 at 12 01 28 PM](https://user-images.githubusercontent.com/107448164/211397240-ec003d4f-8a1e-4cca-85c8-13f00dafb25f.png)

## ✅ Task List

- [x] Link hot tab to Hot Tracks page 
- [x] Change title to "Hot Tracks"
- [x] Create container 
- [x] Create a renderEntry function that will create the song track using DOM
   - [x] Create:
      - [x] Div row that takes up the full width 
      - [x] Div column that takes up 1/3 of space 
         - [x] Create image element and append it 
      - [x] Create Div column that takes up 2/3 of space  
         - [x] H3 for the song name 
         - [x] H4 for the user name 
         - [x] add button 
- [x] Append created function elements into the container 
- [x] Replace image with data image from api 
- [x] Replace song and username with data from api 

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
