### ISSUE TITLE
Feature: User can get playlists of a user 

### ISSUE THREAD

**Issue by jameswu49** [jameswu49/ajax-project#2]
## ⚙️ Feature

User can see another user's playlist 

## 📐 Functionality

When user clicks on a user and clicks on the playlist tab, it will show a list of their playlists to chose from 

## 🖼️ Wireframes

<img width="399" alt="Screenshot 2023-01-09 at 12 13 31 PM" src="https://user-images.githubusercontent.com/107448164/211399322-12382bf1-cb2b-42a4-908d-9a24963768c4.png">

<img width="928" alt="Screenshot 2023-01-09 at 12 13 34 PM" src="https://user-images.githubusercontent.com/107448164/211399333-2eb6a220-f680-44fa-a4b2-2d796a14e8df.png">

![Screenshot 2023-01-12 at 9 39 58 AM](https://user-images.githubusercontent.com/107448164/212139818-e0e11c8f-a86d-41fa-914a-be84e50387a9.png)

![Screenshot 2023-01-12 at 9 40 00 AM](https://user-images.githubusercontent.com/107448164/212139831-ebdb27dd-4731-4a63-8b32-7d5f0a714feb.png)

![Screenshot 2023-01-12 at 9 40 45 AM](https://user-images.githubusercontent.com/107448164/212139898-cfa02b92-1074-4204-826d-c053bece335f.png)

![Screenshot 2023-01-12 at 9 40 51 AM](https://user-images.githubusercontent.com/107448164/212139919-32625da3-ac9a-4bdf-9653-62c036660368.png)

![Screenshot 2023-01-12 at 9 41 11 AM](https://user-images.githubusercontent.com/107448164/212139984-4949e905-dee2-469f-9229-4e1aa890e9ad.png)

![Screenshot 2023-01-12 at 9 41 18 AM](https://user-images.githubusercontent.com/107448164/212139998-ff508d96-75e3-4a99-9158-e96626eff5c5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an array of 5 popular users they can discover from
   - [x] Show off users on discover page for user to pick from that lead to users page  
- [x]  Create xhr request to get playlist data 
- [x] Render the entries using the createTracks function with the playlist data 
- [x] Change image to match the user 
- [x] Create user's page that opens up when you click on a user 
   - [x] Hide the rest of the pages when clicked on 
- [x] Create users playlist page 
   - [x] If there are playlists available
      - [x] Create function that will create a playlist template 
      - [x] Get api data and put it in the function 
   - [] If there are no playlists available, show no playlists available text   

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
