### ISSUE TITLE
Feature: User can see who another user is following

### ISSUE THREAD

**Issue by jameswu49** [jameswu49/ajax-project#3]
## ⚙️ Feature

User will get a list of another user's following list 

## 📐 Functionality

When they click the following tab, they will see a list of who the user is following 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="438" alt="Screenshot 2023-01-09 at 12 12 26 PM" src="https://user-images.githubusercontent.com/107448164/211399146-9e82f911-5513-4a65-a651-c95869b9be36.png">
->

<img width="912" alt="Screenshot 2023-01-09 at 12 12 31 PM" src="https://user-images.githubusercontent.com/107448164/211399171-b630fe49-80b9-4123-ace1-ebe778763fad.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create user following page using template from before 
- [ ] Use user id to get data from api on who they follow 
- [ ] create dom tree to populate following page 
   - [ ] If api data is empty, create not following page 
   - [ ] else, populate with name of the users 

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
