### ISSUE TITLE
Feature: User can see another user's liked songs

### ISSUE THREAD

**Issue by jameswu49** [jameswu49/ajax-project#4]
## ⚙️ Feature

User will get a list of another user's liked songs 

## 📐 Functionality

When liked songs tab is clicked on, user will get a list of the user's liked songs 

## 🖼️ Wireframes

<img width="411" alt="Screenshot 2023-01-09 at 12 15 16 PM" src="https://user-images.githubusercontent.com/107448164/211399646-810762b3-ad78-4f66-ad6e-6006b92ef7a8.png">

<img width="930" alt="Screenshot 2023-01-09 at 12 15 19 PM" src="https://user-images.githubusercontent.com/107448164/211399659-406c84fc-3087-4acd-8a13-8291d32fa2c7.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create liked songs page and container 
- [x] Create function to render entries for liked songs container 
- [x] Get and replace api data for the liked songs container 
   - [x] Create no liked songs if no songs are liked by user 

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
