### ISSUE TITLE
Feature: User can search for songs 

### ISSUE THREAD

**Issue by jameswu49** [jameswu49/ajax-project#5]
## ⚙️ Feature

User can search for songs 

## 📐 Functionality

User can use the search bar to search and gets back a page of results that match their search input 

## 🖼️ Wireframes

<img width="727" alt="Screenshot 2023-01-09 at 12 18 11 PM" src="https://user-images.githubusercontent.com/107448164/211400154-a3df8370-b21c-49b3-ab96-11d60786cb6e.png">

<img width="1276" alt="Screenshot 2023-01-09 at 12 18 29 PM" src="https://user-images.githubusercontent.com/107448164/211400169-b03771fa-40b2-4bc6-b9b7-3e47c9bb35cb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create search page and container 
- [x] Make home page search bar for songs and discover tab search bar for users 
- [x] Create entries for search page using search api data 
   - [x] Create no songs found title  

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
